#!/bin/sh
# Copyright (C) 2020-2022 ASHYELF
# include fundamental function support, you cannot delete this
. $cheader

nsta_up()
{
    /usr/bin/he wifi@nssid:status=disable  >/dev/null
    /usr/bin/he ifname@wisp:status=enable  >/dev/null
    creturn ttrue
}
nssid_up()
{
    /usr/bin/he wifi@nssid:status=enable  >/dev/null
    /usr/bin/he ifname@wisp:status=disable  >/dev/null
    creturn ttrue
}

asta_up()
{
    /usr/bin/he wifi@assid:status=disable  >/dev/null
    /usr/bin/he ifname@wisp2:status=enable  >/dev/null
    creturn ttrue
}
assid_up()
{
    /usr/bin/he wifi@assid:status=enable  >/dev/null
    /usr/bin/he ifname@wisp2:status=disable  >/dev/null
    creturn ttrue
}

# call the method, you cannot delete this
cend

