#!/bin/sh
# Copyright (C) 2020-2022 ASHYELF
# include fundamental function support, you cannot delete this
. $cheader

TTYD=$(which ttyd 2>/dev/null) || true
[ -z "$TTYD" ] && TTYD="/usr/bin/ttyd"
TTYD_PORT=$(/usr/bin/he wui@admin:ttydport 2>/dev/null)
[ -z "$TTYD_PORT" ] && TTYD_PORT="81"


port()
{
    if [ ! -x "$TTYD" ]; then
        creturn NULL
    else
        creturn $TTYD_PORT
    fi
}

setup()
{
    if [ ! -x "$TTYD" ]; then
        logger "ttyd not found, skip service.start: $TTYD"
        creturn ttrue
    else
        TTYD_PID=$(/usr/bin/he land@service.pid[ttyd] 2>/dev/null)
        if [ -z "$TTYD_PID" ]; then
            /usr/bin/he land@service.start[ttyd, wui@ttyd, service] >/dev/null
            sleep 1
        fi
        creturn ttrue
    fi
}
shut()
{
    /usr/bin/he land@service.stop[ttyd] >/dev/null
    creturn ttrue
}
service()
{
    if [ ! -x "$TTYD" ]; then
        logger "ttyd not found, skip service.start: $TTYD"
        creturn terror
    else
        logger "ttyd running: $TTYD -p $TTYD_PORT"
        exec $TTYD -W -p $TTYD_PORT /usr/bin/eline
        creturn tfalse
    fi
}

# call the method, you cannot delete this
cend

