#!/bin/bash
TOPDIR=`pwd`

git status

# core project
if [ -d ${TOPDIR}/project ]; then
    cd ${TOPDIR}/project
    list=`ls`
    for tmp in $list
    do
        if [ -d ${TOPDIR}/project/${tmp}/.git ]; then
            echo "################################################"
            echo "############## status the ${tmp} ###############"
            echo "################################################"
            cd ${TOPDIR}/project/${tmp};git status
        fi
    done
fi
cd ${TOPDIR}

# Custom
for tmp in rice
do
    if [ -d ${TOPDIR}/${tmp}/.git ]; then
        echo "################################################"
        echo "############## status the ${tmp} ###############"
        echo "################################################"
        cd ${TOPDIR}/${tmp};git status
    fi
done


# platform project
if [ -d ${TOPDIR}/config ]; then
    cd ${TOPDIR}/config
    list=`ls`
    for tmp in $list
    do
        if [ -d ${TOPDIR}/config/${tmp}/.git ]; then
            echo "################################################"
            echo "############## status the ${tmp} ###############"
            echo "################################################"
            cd ${TOPDIR}/config/${tmp};git status
        fi
        if [ -d ${TOPDIR}/config/${tmp} ]; then
            sublist=`ls ${TOPDIR}/config/${tmp}`
            for sub in $sublist
            do
                if [ -d ${TOPDIR}/config/${tmp}/${sub}/.git ]; then
                    echo "################################################"
                    echo "############## status the ${tmp}/${sub} ###############"
                    echo "################################################"
                    cd ${TOPDIR}/config/${tmp}/${sub};git status
                fi
            done
        fi
    done
fi
cd ${TOPDIR}


