#!/bin/bash
TOPDIR=`pwd`

git pull

# core project
if [ -d ${TOPDIR}/project ]; then
    cd ${TOPDIR}/project
    list=`ls`
    for tmp in $list
    do
        if [ -d ${TOPDIR}/project/${tmp} ]; then
            echo "################################################"
            echo "############## update the ${tmp} ###############"
            echo "################################################"
            cd ${TOPDIR}/project/${tmp};git pull
        fi
    done
fi
cd ${TOPDIR}

# Custom
for tmp in rice
do
    if [ -d ${TOPDIR}/${tmp} ]; then
        echo "################################################"
        echo "############## update the ${tmp} ###############"
        echo "################################################"
        cd ${TOPDIR}/${tmp};git pull
    fi
done

# platform project
if [ -d ${TOPDIR}/config ]; then
    cd ${TOPDIR}/config
    list=`ls`
    for tmp in $list
    do
        if [ -d ${TOPDIR}/config/${tmp} ]; then
            echo "################################################"
            echo "############## update the ${tmp} ###############"
            echo "################################################"
            cd ${TOPDIR}/config/${tmp};git pull
        fi
    done
fi
cd ${TOPDIR}


