#!/bin/bash
TOPDIR=`pwd`
PRJ_LIST=`ls ./project`
PLAT_LIST=`ls ./config`

for plat in $PLAT_LIST
do
    if [ ${plat} == "srkw" ] || [ ${plat} == "rkw" ]; then
        DIR_ROOT=${plat}/openwrt/build_dir
    else
        DIR_ROOT=${plat}/build_dir
    fi
    if [ -d ${DIR_ROOT} ]
    then
        DIR_LIST=`ls ${DIR_ROOT}`
        for dir in $DIR_LIST
        do
            echo "rm -fr ${DIR_ROOT}/${dir}/skinos_*"
            rm -fr ${DIR_ROOT}/${dir}/skinos_*
            echo "rm -fr ${DIR_ROOT}/${dir}/root*"
            rm -fr ${DIR_ROOT}/${dir}/root*
        done
    fi
done

