#!/bin/bash
TOPDIR=`pwd`
PRJ_LIST=`ls ./project`
PLAT_LIST=`ls ./config`

for plat in $PLAT_LIST
do
    if [ ${plat} == "srkw" ] || [ ${plat} == "rkw" ]; then
        SDK_ROOT=${plat}/openwrt
        DIR_ROOT=${SDK_ROOT}/build_dir
    else
        SDK_ROOT=${plat}
        DIR_ROOT=${SDK_ROOT}/build_dir
    fi
    if [ -d ${DIR_ROOT} ]
    then
        DIR_LIST=`ls ${DIR_ROOT}`
        for dir in $DIR_LIST
        do
            if [ $# -gt 0 ]; then
                for name in "$@"
                do
                    echo "rm -fr ${DIR_ROOT}/${dir}/skinos_${name}*"
                    rm -fr ${DIR_ROOT}/${dir}/skinos_${name}*
                done
            else
                # Full skinos/root wipe only for OpenWrt musl/glibc platforms
                if [ "${plat}" = "swrt5" ] || [ "${plat}" = "wrt5" ]; then
                    echo "rm -fr ${DIR_ROOT}/${dir}/skinos_*"
                    rm -fr ${DIR_ROOT}/${dir}/skinos_*
                    echo "rm -fr ${DIR_ROOT}/${dir}/root*"
                    rm -fr ${DIR_ROOT}/${dir}/root*
                fi
            fi
        done
    fi
    # Full clean only: drop shared package feeds.
    # Same CPU arch (e.g. mipsel_24kc) with different libc (musl/glibc)
    # overwrite the same busybox-*.apk path; leftover apks mix into the next image.
    if [ $# -eq 0 ]; then
        if [ -d ${SDK_ROOT}/staging_dir/packages ]; then
            echo "rm -fr ${SDK_ROOT}/staging_dir/packages"
            rm -fr ${SDK_ROOT}/staging_dir/packages
        fi
        if [ -d ${SDK_ROOT}/bin/packages ]; then
            echo "rm -fr ${SDK_ROOT}/bin/packages"
            rm -fr ${SDK_ROOT}/bin/packages
        fi
    fi
done
