# **************************************** #
# ******* Directory Definition *********** #
# **************************************** #
# bootloader
gpBOOT_DIR := ${gPLATFORM_DIR}/uboot
export gpBOOT_DIR

# **************************************** #
# ************ File Definition *********** #
# **************************************** #
# SDK的配置文件位置
gSDK_CFGFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/sdk.config" ]; \
	then echo ${gSCOPE_DIR}/sdk.config; \
	elif [ -f "${gCUSTOM_DIR}/sdk.config" ]; \
	then echo ${gCUSTOM_DIR}/sdk.config; \
	elif [ -f "${gHARDWARE_DIR}/sdk.config" ]; \
	then echo ${gHARDWARE_DIR}/sdk.config;\
	else echo ${gPLATFORM_DIR}/sdk.config;\
	fi)
gpBOOT_CFGFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/boot.config" ]; \
	then echo ${gSCOPE_DIR}/boot.config; \
	elif [ -f "${gCUSTOM_DIR}/boot.config" ]; \
	then echo ${gCUSTOM_DIR}/boot.config; \
	elif [ -f "${gHARDWARE_DIR}/boot.config" ]; \
	then echo ${gHARDWARE_DIR}/boot.config;\
	else echo ${gPLATFORM_DIR}/boot.config;\
	fi)
gpKERNEL_CFGFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/kernel.config" ]; \
	then echo ${gSCOPE_DIR}/kernel.config; \
	elif [ -f "${gCUSTOM_DIR}/kernel.config" ]; \
	then echo ${gCUSTOM_DIR}/kernel.config; \
	elif [ -f "${gHARDWARE_DIR}/kernel.config" ]; \
	then echo ${gHARDWARE_DIR}/kernel.config;\
	else echo ${gPLATFORM_DIR}/kernel.config;\
	fi)
gSKIN_MKFILE := $(shell \
	if [ -f "${gSCOPE_DIR}/skin.mk" ]; \
	then echo ${gSCOPE_DIR}/skin.mk; \
	elif [ -f "${gCUSTOM_DIR}/skin.mk" ]; \
	then echo ${gCUSTOM_DIR}/skin.mk; \
	elif [ -f "${gHARDWARE_DIR}/skin.mk" ]; \
	then echo ${gHARDWARE_DIR}/skin.mk;\
	else echo ${gPLATFORM_DIR}/skin.mk;\
	fi)
export gSDK_CFGFILE gpBOOT_CFGFILE gpKERNEL_CFGFILE
export gSKIN_MKFILE
gpKERNEL_SDK_CFGFILE := ${gSDK_DIR}/target/linux/ramips/mt7621/config-6.12
export gpKERNEL_SDK_CFGFILE

# ********************************** #
# ******** Platform macro ********** #
# ********************************** #
gpUPGRADE_IMAGE = ${gSDK_DIR}/bin/targets/ramips/mt7621/openwrt-ramips-mt7621-lcx_v525w-squashfs-sysupgrade.bin
#gpUPGRADE_IMAGE = ${gSDK_DIR}/bin/targets/ramips/mt7621-glibc/openwrt-ramips-mt7621-lcx_v525w-squashfs-sysupgrade.bin
export gpUPGRADE_IMAGE
gBALE_MAKEFILE = ${gPLATFORM_DIR}/pack.makefile
export gBALE_MAKEFILE

# **************************************** #
# ********* compile environment ********** #
# **************************************** #
# misc cross environment
gLIB_CFLAGS := -I${gINSTALL_DIR}/include -I${gHARDWARE_DIR}/include -Wno-format-truncation -Wno-unused-result -Wno-stringop-truncation
gLIB_LDFLAGS := -L${gINSTALL_DIR}/lib -L${gHARDWARE_DIR}/rootfs/lib -lcrypto -lssl -levent
gCOM_CFLAGS := -I${gINSTALL_DIR}/include -I${gHARDWARE_DIR}/include -Wno-format-truncation -Wno-unused-result -Wno-stringop-truncation
gCOM_LDFLAGS := -L${gINSTALL_DIR}/lib -L${gHARDWARE_DIR}/rootfs/lib -lskin -lcrypto -lssl -levent
gEXE_CFLAGS := -I${gINSTALL_DIR}/include -I${gHARDWARE_DIR}/include -Wno-format-truncation -Wno-unused-result -Wno-stringop-truncation
gEXE_LDFLAGS := -L${gINSTALL_DIR}/lib -L${gHARDWARE_DIR}/rootfs/lib -lskin -ldl -lcrypto -lssl -levent
export gLIB_CFLAGS gLIB_LDFLAGS
export gCOM_CFLAGS gCOM_LDFLAGS
export gEXE_CFLAGS gEXE_LDFLAGS



