#!/bin/sh
# Copyright (C) 2020-2022 ASHYELF
# include fundamental function support, you cannot delete this
. $cheader

setup()
{
    # set ip forward
    sudo sysctl -w net.ipv4.ip_forward=1
    LANDDIR=/usr/share/skinos/land
    
    # mkdir basic directory
    TROOT=/tmp/skinos
    PROJECT_REG_DIR=$TROOT/.reg
    PROJECT_SER_DIR=$TROOT/.ser
    PROJECT_COM_DIR=$TROOT/.com
    PROJECT_CAH_DIR=$TROOT/.cah
    PROJECT_CONF_DIR=$TROOT/.conf

    MROOT=/mnt/skinos
    PROJECT_CFG_DIR=$MROOT/config
    PROJECT_DBS_DIR=$MROOT/dbs
    PROJECT_OEM_DIR=$MROOT/.oem
    PROJECT_INT_DIR=$MROOT/internal
    PROJECT_APP_DIR=$PROJECT_INT_DIR/skinos
    
    VROOT=/var/skinos

    mkdir -p $TROOT
    chmod a+rwx $TROOT
    mkdir -p $PROJECT_REG_DIR
    mkdir -p $PROJECT_SER_DIR
    mkdir -p $PROJECT_COM_DIR
    mkdir -p $PROJECT_CAH_DIR
    mkdir -p $PROJECT_CONF_DIR

    sudo mkdir -p $MROOT
    sudo chmod a+rwx $MROOT
    mkdir -p $PROJECT_DBS_DIR
    mkdir -p $PROJECT_CFG_DIR
    mkdir -p $PROJECT_OEM_DIR
    mkdir -p $PROJECT_INT_DIR

    sudo mkdir -p $VROOT
    sudo chmod a+rwx $VROOT

    # load the basic ko
    if [ -e /usr/prj/pdriver/crackid.ko ]; then
        insmod /usr/prj/pdriver/crackid.ko
    fi
    # make the register value default
    RAND=`date +%N`
    $LANDDIR/bin/he land@register.set_int[rand,$RAND]
    $LANDDIR/bin/he land@register.set_string[platform,$gPLATFORM]
    $LANDDIR/bin/he land@register.set_string[hardware,$gHARDWARE]
    $LANDDIR/bin/he land@register.set_string[custom,$gCUSTOM]
    $LANDDIR/bin/he land@register.set_string[scope,$gSCOPE]
    $LANDDIR/bin/he land@register.set_string[version,$gVERSION]
    NETDEV=`$LANDDIR/bin/he arch@data:local_netdev`
    if [ "X${NETDEV}" = "X" ]; then
        NETDEV=`ip -o route get 8.8.8.8 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}'`
    fi
    if [ "X${NETDEV}" != "X" ]; then
        $LANDDIR/bin/he land@register.set_string[local_ifname,ifname@lan]
        $LANDDIR/bin/he land@register.set_string[local_netdev,$NETDEV]
    fi
    MODEL=`$LANDDIR/bin/he arch@data:model`
    $LANDDIR/bin/he land@register.set_string[model,$MODEL]
    MODEL=`$LANDDIR/bin/he arch@data:cmodel`
    $LANDDIR/bin/he land@register.set_string[cmodel,$MODEL]
    MAC=`$LANDDIR/bin/he arch@data:mac`
    $LANDDIR/bin/he land@register.set_string[mac,$MAC]
    MACID=`$LANDDIR/bin/he arch@data:macid`
    if [ "X${MACID}" != "X" ]; then
        $LANDDIR/bin/he land@register.set_string[macid,$MACID]
    fi
    FEATURES=`$LANDDIR/bin/he arch@data:features`
    if [ "X${FEATURES}" != "X" ]; then
        $LANDDIR/bin/he land@register.set_string[features,$FEATURES]
    fi
    MAGIC=`$LANDDIR/bin/he arch@data:magic`
    if [ "X${MAGIC}" != "X" ]; then
        $LANDDIR/bin/he land@register.set_string[magic,$MAGIC]
    fi
    DATECODE=`$LANDDIR/bin/he arch@data:datecode`
    if [ "X${DATECODE}" = "X" ]; then
        DATECODE=`$LANDDIR/bin/he arch@data:datacode`
    fi
    if [ "X${DATECODE}" != "X" ]; then
        $LANDDIR/bin/he land@register.set_string[datecode,$DATECODE]
    fi
    OEM=`$LANDDIR/bin/he arch@data:oem`
    if [ "X${OEM}" != "X" ]; then
        $LANDDIR/bin/he land@register.set_string[oem,$OEM]
    fi
    # default the configure if order
    if [ -e $PROJECT_CFG_DIR/.customv8 ]; then
    	echo "mount the configure"
    else
    	echo "clear the configure"
        rm -fr $PROJECT_CFG_DIR/*
        echo "$gPLATFORM-$gHARDWARE-$gCUSTOM-$gSCOPE" > $PROJECT_CFG_DIR/.customv8
    fi
    if [ -e $PROJECT_INT_DIR/.customv8 ]; then
    	echo "mount the interval"
	else
    	echo "clear the interval"
		rm -fr $PROJECT_INT_DIR/*
        echo "$gPLATFORM-$gHARDWARE-$gCUSTOM-$gSCOPE" > $PROJECT_INT_DIR/.customv8
    fi

    NAME=`hostname`
    $LANDDIR/bin/he land@machine:name=$NAME

    # After config dir is ready: restore config write lock from file config
    CFGLOCK=`$LANDDIR/bin/he arch@data:config`
    if [ "X${CFGLOCK}" = "Xdisable" ]; then
        $LANDDIR/bin/he land@register.set_int[config_lock,1]
    else
        $LANDDIR/bin/he land@register.set_int[config_lock,0]
    fi

    creturn ttrue
}

config_lock()
{
    LANDDIR=/usr/share/skinos/land
    # Persist while unlocked, then set runtime lock
    $LANDDIR/bin/he 'arch@data:config=disable'
    $LANDDIR/bin/he land@register.set_int[config_lock,1]
    creturn ttrue
}

config_unlock()
{
    LANDDIR=/usr/share/skinos/land
    # Clear runtime lock first, then persist
    $LANDDIR/bin/he land@register.set_int[config_lock,0]
    $LANDDIR/bin/he 'arch@data:config=enable'
    creturn ttrue
}

shut()
{
    sync
    creturn ttrue
}

# call the method, you cannot delete this
cend

